"""Security headers middleware (OWASP hardening).

Adds the following headers to every response:
  Strict-Transport-Security   — forces HTTPS for 2 years + subdomains
  X-Content-Type-Options      — prevents MIME-type sniffing
  X-Frame-Options             — blocks clickjacking
  X-XSS-Protection            — legacy XSS filter (belt-and-suspenders)
  Referrer-Policy             — limits referrer information leakage
  Permissions-Policy          — disables unused browser APIs
  Content-Security-Policy     — restricts script/style sources

The CSP is intentionally strict.  If the dashboard ever moves to a CDN
origin, update DASHBOARD_ORIGIN in the calling app and pass it here via
the constructor.

Rate-limiting note: real rate limiting is handled by the API gateway /
ingress (nginx / Kong / AWS WAF) upstream.  This middleware adds a
Retry-After header on 429 responses generated by those layers.
"""

from __future__ import annotations

from typing import Callable

from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.types import ASGIApp

# CSP directives that apply to the API itself.
# The dashboard origin is allowed as a frame-ancestor so the embedded
# chart widgets can be iframed from the React app (same-site only).
_CSP = (
    "default-src 'none'; "
    "frame-ancestors 'none'; "
    "base-uri 'none'; "
    "form-action 'none'"
)


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """Inject OWASP-recommended security response headers."""

    _HEADERS: dict[str, str] = {
        "Strict-Transport-Security": "max-age=63072000; includeSubDomains; preload",
        "X-Content-Type-Options":    "nosniff",
        "X-Frame-Options":           "DENY",
        "X-XSS-Protection":          "1; mode=block",
        "Referrer-Policy":           "strict-origin-when-cross-origin",
        "Permissions-Policy": (
            "camera=(), microphone=(), geolocation=(), "
            "payment=(), usb=(), accelerometer=()"
        ),
        "Content-Security-Policy":   _CSP,
    }

    def __init__(self, app: ASGIApp) -> None:
        super().__init__(app)

    async def dispatch(self, request: Request, call_next: Callable) -> Response:  # type: ignore[override]
        response = await call_next(request)
        for header, value in self._HEADERS.items():
            response.headers[header] = value
        # Remove headers that leak server implementation details
        response.headers.pop("Server", None)
        response.headers.pop("X-Powered-By", None)
        return response
